# Calcul scientifique: [numpy](https://numpy.org/doc/stable/)


In [1]:
#!pip install numpy
import numpy as np

[Documentation de numpy](https://numpy.org/doc/stable/)


---

<h1> Sommaire <span class="tocSkip"> </span> </h1>
<div class ="toc"> <ul class ="toc-item">
<li > <span><a href="#Bases-sur-les-tableaux-numpy" data-toc-modified-id="Bases-sur-les-tableaux-numpy-1">
<span class="toc-item-num" > 1 &nbsp;&nbsp; </span> Bases sur les tableaux <code> numpy </code > </a>
</span> <ul class="toc-item"> <li>
<span> <a href="#Rappels-sur-les-collections-de-base-en-Python" data-toc-modified-id="Rappels-sur-les-collections-de-base-en-Python-1.1">
<span class="toc-item-num"> 1.1 &nbsp;&nbsp; </span> Rappels sur les collections de base en Python </a> </span> </li>
<li> <span> <a href="#Bases-sur-les-tableaux-numpy" data-toc-modified-id="Bases-sur-les-tableaux-numpy-1.2" >
<span class="toc-item-num"> 1.2 &nbsp;&nbsp; </span> Bases sur les tableaux
<code> numpy </code> </a> </span> </li> </ul> </li > <li>
<span> <a href="#Créer-des-tableaux" data-toc-modified-id="Créer-des-tableaux-2">
<span class ="toc-item-num" > 2 &nbsp;&nbsp; </span> Créer des tableaux </a> </span> </li> <li> 
<span> <a href="#Manipuler-des-tableaux" data-toc-modified-id="Manipuler-des-tableaux-3" > 
<span class="toc-item-num" > 3 &nbsp;&nbsp; </span> Manipuler des tableaux </a> </span>
<ul class="toc-item"> <li> <span> <a href="#Dimensions-(shape)" data-toc-modified-id="Dimensions-(shape)-3.1"> 
<span class="toc-item-num"> 3.1 &nbsp; &nbsp; </span> Dimensions ( <code> shape </code> ) </a> </span> </li>
<li> <span> <a href="#Opérations-de-base" data-toc-modified-id="Opérations-de-base-3.2">
<span class="toc-item-num" > 3.2 &nbsp; &nbsp; </span > Opérations de base </a> </span> </li>
<li> <span> <a href="#Fonctions-universelles-(ufunc)" data-toc-modified-id="Fonctions-universelles-(ufunc)-3.3"> 
<span class="toc-item-num"> 3.3 &nbsp; &nbsp; </span> Fonctions universelles ( <em> ufunc </em> ) </a> </span> </li>
<li> <span> <a href="#Indexation-de-base" data-toc-modified-id="Indexation-de-base-3.4"> 
<span class ="toc-item-num"> 3.4 &nbsp; &nbsp; </span > Indexation de base </a> </span> <ul class ="toc-item"> 
<li> <span> <a href="#Accès-aux-éléments" data-toc-modified-id="Accès-aux-éléments-3.4.1"> <span class="toc-item-num"> 3.4.1 &nbsp; &nbsp; </span> Accès aux éléments </a> </span> </li> <li> <span> <a href="#Les-slices" data-toc-modified-id="Les-slices-3.4.2"> <span class="toc-item-num"> 3.4.2 &nbsp; &nbsp; </span> Les slices </a> </span> </li> </ul> </li> <li> <span> <a href="#Entrées/sorties" data-toc-modified-id="Entrées/sorties-3.5"> <span class="toc-item-num"> 3.5 &nbsp; &nbsp; </span> Entrées / sorties </a> </span> <ul class="toc-item"> <li> <span> <a href="#Formats-spécifiques-à-numpy:-npy-et-npz" data-toc-modified-id="Formats-spécifiques-à-numpy:-npy-et-npz-3.5.1"> <span class="toc-item-num"> 3.5.1 &nbsp; &nbsp; </span> Formats spécifiques à numpy: npy et npz </a> </span> </li> <li> <span> <a href="#Format-générique-csv" data-toc-modified-id="Format-générique-csv-3.5.2"> <span class="toc-item-num"> 3.5.2 &nbsp; &nbsp; </span> Format générique csv </a> </span> </li> </ul> </li> <li> <span> <a href="#Autres-fonctions-de-base" data-toc-modified-id="Autres-fonctions-de-base-3.6"> <span class ="toc-item-num" > 3.6 &nbsp; &nbsp; </span> Autres fonctions de base </a> </span> </li> </ul> </li> 
<li> <span> <a href="#Manipulations-avancées" data-toc-modified-id="Manipulations-avancées-4"> 
<span class ="toc-item-num"> 4 &nbsp; &nbsp; </span> Manipulations avancées </a> </span>
<ul class="toc-item"> <li> <span> <a href="#Broadcasting" data-toc-modified-id="Broadcasting-4.1">
<span class="toc-item-num"> 4.1 &nbsp; &nbsp; </span> Broadcasting </a> </span> </li> <li> <span> <a href="#Indexation-avancée" data-toc-modified-id="Indexation-avancée-4.2"> <span class ="toc-item-num"> 4.2 &nbsp; &nbsp; </span> Indexation avancée </a> </span> 
<ul class="toc-item"><li><span> <a href="#Indexation-avancée-avec-des-séquences-d'entiers" data-toc-modified-id="Indexation-avancée-avec-des-séquences-d'entiers-4.2.1">
<span class="toc-item-num"> 4.2.1 &nbsp;&nbsp; </span> Indexation avancée avec des séquences d' entiers</a></span></li>
<li><span><a href="#Indexation-avancée-avec-des-booléens" data-toc-modified-id="Indexation-avancée-avec-des-booléens-4.2.2">
<span class="toc-item-num">4.2.2 &nbsp;&nbsp;</span>Indexation avancée avec des booléens</a></span></li></ul></li></ul</li>
<li><span><a href="#Vues-et-copies" data-toc-modified-id="Vues-et-copies-5">
<span class="toc-item-num">5 &nbsp;&nbsp;</span>
Vues et copies</a></span></li></ul>
<li> <span> <a href="#Quelques-mots-sur-panda" data-toc-modified-id="#Quelques-mots-sur-panda-6"> 
<span class ="toc-item-num"> 6 &nbsp; &nbsp; </span> Quelques mots sur `panda`</a> </span></li></ul>
</div>

---
## Bases sur les tableaux `numpy`

### Rappels sur les collections de base en Python

* Tuples: indexation avec des entiers, contenu figé
* Listes: indexation avec des entiers, contenu modifiable
* Dictionnaires: indexation avec des clés, contenu modifiable

Remarques:
* Les éléments peuvent être de types différents.
* Accès aux éléments via les crochets `[]`.

In [2]:
un_tuple = ('Bonjour', 2.1)
print('Un tuple:', un_tuple)
## ***********        Remplissez les trous     *************
print('Longueur:', len(un_tuple))
print('Premier élément:', un_tuple[0])
print('Deuxième élément:', un_tuple[1])
print('Concaténation:', un_tuple + ('Hello', 'World'))
## ~~~~~~~~~~     Déboguez     ~~~~~~~~~~
une_liste = ['Bonjour', 2.1]
print('Une liste:', une_liste)
#print(f'Une liste: {une_liste}')
#print('Une liste: {}'.format(une_liste))
#print('Une liste: % s'% une_liste)
## ~~~~~~~~~~     Déboguez     ~~~~~~~~~~
for i in range(len(une_liste)):
    print(f'Élément {i}: {une_liste[i]}')
print('Concaténation:', une_liste + ['Hello', 'World'])
une_liste[1] = 1
une_liste.append('**')
print('Après modification:', une_liste)
un_dict = {'Valentin': 25, 'Arthur': 42, 123: 'hello'}
un_dict[(12, 'bonjour')] = 'v'
# print(un_dict)
## ~~~~~~~~~~     Déboguez     ~~~~~~~~~~
for k in un_dict.keys():
    print(f'Clé {k}, valeur {un_dict[k]}')

Un tuple: ('Bonjour', 2.1)
Longueur: 2
Premier élément: Bonjour
Deuxième élément: 2.1
Concaténation: ('Bonjour', 2.1, 'Hello', 'World')
Une liste: ['Bonjour', 2.1]
Élément 0: Bonjour
Élément 1: 2.1
Concaténation: ['Bonjour', 2.1, 'Hello', 'World']
Après modification: ['Bonjour', 1, '**']
Clé Valentin, valeur 25
Clé Arthur, valeur 42
Clé 123, valeur hello
Clé (12, 'bonjour'), valeur v


### Bases sur les tableaux `numpy`

#### Généralités
##### Propriétés fondamentales
- Taille des tableaux fixée à la création. Changer le nombre d’éléments
d’un tableau = créer un nouveau tableau et supprimer l’ancien.
- Tous les éléments d’un tableau sont de même type.
- Les opérations ont des syntaxes invariables suivant les dimensions des
tableaux.
##### Les 2 concepts fondamentaux de Numpy :
- La vectorisation : Numpy est optimisé pour ne jamais utiliser de boucles.
- La diffusion (broadcasting) : Numpy gère les différences de tailles de tableaux
durant les opérations arithmétiques de façon optimale. 

#### La pratique

Remarque de notation
- Pour utiliser numpy, il est recommandé d’importer le module avec la syntaxe :
``import numpy as np``
- Ensuite tous les objets de numpy seront appelés avec
``np.objet_numpy.``
- Par commodité, nous n’avons pas recopié systématiquement l’instruction d’importation dans les exemples. Partout dans ce cours numpy est
importé sous le diminutif ``np.``

#### Objet ''ndarray''
**Propriétés**
- Collection N-dimensions d’éléments de même type continûment
représentés en mémoire (un seul segment).
- L’indexation d’un tableau numpy commence à **0**.
- Les dimensions sont accessibles par l’attribut **shape**.
- Le type des données est accessible par l’attribut **dtype**.

```python
  import numpy as np
  a = np.array([[1,2,3],[4,5,6]])
  a[0,0]
  1
  a.shape
  (2, 3)
  a.dtype
  dtype('int64')
```

* objets de la classe `numpy.ndarray`
* indexation avec crochets `[]`
* éléments d'un seul type : le data type `dtype`
* multidimensionnel
* nombre d'éléments fixé à la création

Exemple: un tableau 1D

In [3]:
a = np.array([1, 2, 3.4])
print(a)
print(type(a))
print(a.dtype)
print(a.ndim)  # Nombre de dimensions
print(a.size)  # Nombre d'éléments
print(a.shape)  # Dimensions

[1.  2.  3.4]
<class 'numpy.ndarray'>
float64
1
3
(3,)


Exemple: un tableau 2D

In [4]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)
print(type(a))
print(a.dtype)
print(a.ndim)  # Nombre de dimensions
print(a.size)  # Nombre d'éléments
print(a.shape)  # Dimensions

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
int64
2
6
(2, 3)


## Créer des tableaux
Nombreuses fonctions!
Quelques exemples utiles.

In [5]:
## ***********        Remplissez les trous     *************
print('*' * 30)
a = np.array([1, 2, 3.4])
print(a.dtype)

******************************
float64


In [6]:
print('*' * 30)

******************************


In [7]:
print(np.zeros((3, 4)))
print('*' * 30)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
******************************


In [8]:
uns = np.ones((2, 5), dtype=int)
print(uns, uns.dtype)
print('*' * 30)

[[1 1 1 1 1]
 [1 1 1 1 1]] int64
******************************


In [9]:
uns = np.ones((2, 5), dtype=np.int32)
print(uns, uns.dtype)
print('*' * 30)

[[1 1 1 1 1]
 [1 1 1 1 1]] int32
******************************


In [10]:
print(np.empty([3, 4], dtype=bool))
print(np.diag([2, 5, 6]))
print(np.identity(3))
print(np.eye(3, 5))
print(np.random.randint(low=3, high=7, size=(2, 10)))
#print(np.random.randint(3, 7, (2,10)))
print(np.arange(10))  # array + range =arange
print(np.arange(start=3, stop=19, step=2))  # array + range =arange
print(np.linspace(start=0, stop=1, num=9))

[[False False False False]
 [False False False False]
 [False False False False]]
[[2 0 0]
 [0 5 0]
 [0 0 6]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]
[[6 6 6 6 5 4 6 4 4 5]
 [4 3 3 6 4 4 6 3 3 3]]
[0 1 2 3 4 5 6 7 8 9]
[ 3  5  7  9 11 13 15 17]
[0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875 1.   ]


## Manipuler des tableaux
### Dimensions (`shape`)

In [11]:
a = np.random.randn(4, 5)
print(a)
print("Dimensions:", a.shape)
print("Nombre de lignes", a.shape[0])
print("Nombre de colonnes", a.shape[1])

[[-2.2385403  -1.69208651 -0.07002794  1.211029   -0.71361621]
 [ 0.94162514  1.42461397  0.92307966 -0.49293688  0.0620376 ]
 [-0.52577465 -0.3697924  -2.46580989 -0.38438146  0.4990371 ]
 [-0.0302144  -0.75013312 -1.10914985 -1.92327823  0.39780296]]
Dimensions: (4, 5)
Nombre de lignes 4
Nombre de colonnes 5


Le nombre d 'éléments étant fixés, on peut facilement redimensionner un tableau (*reshape*).

In [12]:
# Un tableau 1D
a = np.arange(24)
print(a)
print(a.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
(24,)


In [13]:
# Redimensionnement en tableau 3D
b = a.reshape(2, 3, 4)
print(a.shape)
print(b.shape)
##%%
print(b)
c = b.reshape(4, 6)
print(c)

(24,)
(2, 3, 4)
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [14]:
# Redimensionnement en tableau 2D
b = a.reshape(-1, 12)  # -1 pour laisser le calcul se faire selon une des dimensions
print(a.shape)
print(b.shape)
##%%
print(b)
##%%
b = a.reshape(2, 4, -1)
print(b.shape)
##%%
print(b)

(24,)
(2, 12)
[[ 0  1  2  3  4  5  6  7  8  9 10 11]
 [12 13 14 15 16 17 18 19 20 21 22 23]]
(2, 4, 3)
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


### Opérations de base
Addition, soustraction, multiplication, division, puissance, etc.:

* entre tableaux de mêmes dimensions
* coefficient par coefficient

In [15]:
a = np.arange(6).reshape(2, 3)
b = np.arange(6, 12).reshape(2, 3)
print(a)
print(b)
# addition
print(a + b)
print(a)
print(b)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]
[[ 6  8 10]
 [12 14 16]]
[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [16]:
# Soustraction
print(a - b)
print(a)
print(b)

[[-6 -6 -6]
 [-6 -6 -6]]
[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [17]:
# Multiplication
print(a * b)
print(a)
print(b)
# Division
print(a / b)
# Puissance
print(a ** b)

[[ 0  7 16]
 [27 40 55]]
[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]
[[0.         0.14285714 0.25      ]
 [0.33333333 0.4        0.45454545]]
[[       0        1      256]
 [   19683  1048576 48828125]]


Produit matriciel avec ` @ ` ou ` dot() `

In [18]:
a = np.arange(6).reshape(2, 3)
b = np.arange(12).reshape(3, 4)
print(a)
print(b)
print(a @ b)  # Opérateur
print(np.matmul(a, b))  # fonction de numpy
print(np.dot(a, b))  # fonction de numpy
print(a.dot(b))  # méthode de np.ndarray
# équivalent pour les matrices, pas pour les tenseurs

[[0 1 2]
 [3 4 5]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[20 23 26 29]
 [56 68 80 92]]
[[20 23 26 29]
 [56 68 80 92]]
[[20 23 26 29]
 [56 68 80 92]]
[[20 23 26 29]
 [56 68 80 92]]


### Fonctions universelles (*ufunc*)

$\equiv$ fonctions qui s'appliquent à des tableaux numpy élément par élément.

Voir [documentation complète](https://numpy.org/doc/stable/reference/ufuncs.html).

In [19]:
a = np.arange(10) ** 2
b = np.sqrt(a)
print('a =', a)
print('b =', b)

a = [ 0  1  4  9 16 25 36 49 64 81]
b = [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


Il existe de nombreuses fonctions universelles:
* opérateurs précédents (*, +, /, **, etc.)
* fonctions mathématiques (add, abs, log, sign, etc.)
* fonctions trigonométriques (cos, sin, etc.)
* fonctions de manipulation de bits (bitwise_and, etc.)
* fonctions de comparaisons de deux tableaux (greater, logical_and, maximum, etc.)
* fonctions pour les flottants (isinf, isnan, floor, ceil, etc.)

[Liste des fonctions universelles disponibles dans numpy](https://numpy.org/doc/stable/reference/ufuncs.html#available-ufuncs)
### Indexation de base
Idées principales:
* utiliser les crochets `a[..., ..., ...]`
* utiliser les *slices* de la forme `start:stop:step`
#### Accès aux éléments
Dans un tableau à $n$ dimensions, on accède à l'élément d'indices $(i_1, i_2, \ldots, i_n)$ via la notation $[i_1, i_2, \ldots, i_n]$.


In [20]:
a = np.arange(6).reshape(2, -1)
print(a)
print(a[1, 2])
## ~~~~~~~~~~     Déboguez     ~~~~~~~~~~
for i in range(a.shape[0]):
    for j in range(a.shape[1]):
        print(f'a[{i}, {j}] = {a[i, j]}')

[[0 1 2]
 [3 4 5]]
5
a[0, 0] = 0
a[0, 1] = 1
a[0, 2] = 2
a[1, 0] = 3
a[1, 1] = 4
a[1, 2] = 5


In [21]:
for i in range(a.shape[0]):
    for j in range(a.shape[1]):
        if a[i, j] % 2 == 0:
            a[i, j] = -1
print(a)

[[-1  1 -1]
 [ 3 -1  5]]


Les indices négatifs désignent les éléments à partir de la fin (`-1` pour le dernier, `-2` pour l'avant dernier, etc.)

In [22]:
print(a)
print(a[0, -1])
print(a[-1, -3])

[[-1  1 -1]
 [ 3 -1  5]]
-1
3


Remarque: utiliser une seule paire de crochet avec $n$ indices ou $n$ paires de crochets avec un seul indice donne le même résultat mais la première méthode est plus efficace.

In [23]:
a = np.random.randn(200, 100)
print(a[123, -45], a[123][-45])
%timeit a[123, -45]
%timeit a[123][-45]

-0.01738654258700574 -0.01738654258700574
142 ns ± 34 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)
282 ns ± 35.2 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


#### Les slices
Sélection d'un ensemble d'indices via `start:stop:step` ou `start:stop`:

* indice de début (inclus) `start`
* indice de fin (exclus): `stop`
* pas `step`

`start` et `stop` peuvent être omis.

In [24]:
a = np.arange(42).reshape(6, 7)
print(a)

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]
 [35 36 37 38 39 40 41]]


In [25]:
print("ligne 3:", a[3, :])
print("colonne 5:", a[:, 5])

ligne 3: [21 22 23 24 25 26 27]
colonne 5: [ 5 12 19 26 33 40]


In [26]:
print(a)
print("dernière ligne:", a[-1, :])
print("avant dernière colonne:", a[:, -2])

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]
 [35 36 37 38 39 40 41]]
dernière ligne: [35 36 37 38 39 40 41]
avant dernière colonne: [ 5 12 19 26 33 40]


In [27]:
print(a)
print("Sous-matrice des lignes 2 à 4 et colonnes 1 à 5:")
print(a[2:5, 1:6])

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]
 [35 36 37 38 39 40 41]]
Sous-matrice des lignes 2 à 4 et colonnes 1 à 5:
[[15 16 17 18 19]
 [22 23 24 25 26]
 [29 30 31 32 33]]


In [28]:
print(a)
print("Sous-matrice des 5 premières lignes et colonnes 2 à fin:")
print(a[:5, 2:])

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]
 [35 36 37 38 39 40 41]]
Sous-matrice des 5 premières lignes et colonnes 2 à fin:
[[ 2  3  4  5  6]
 [ 9 10 11 12 13]
 [16 17 18 19 20]
 [23 24 25 26 27]
 [30 31 32 33 34]]


In [29]:
print(a)
print("une colonne sur 2 des colonnes 1 à 5:")
print(a[:, 1:6:2])
print("les colonnes 5, 4, 3:")
print(a[:, 5:2:-1])

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]
 [35 36 37 38 39 40 41]]
une colonne sur 2 des colonnes 1 à 5:
[[ 1  3  5]
 [ 8 10 12]
 [15 17 19]
 [22 24 26]
 [29 31 33]
 [36 38 40]]
les colonnes 5, 4, 3:
[[ 5  4  3]
 [12 11 10]
 [19 18 17]
 [26 25 24]
 [33 32 31]
 [40 39 38]]


### Entrées/sorties
* Format spécifique: npy/npz
* Formats génériques: txt, csv, json, etc.

#### Formats spécifiques à numpy: npy et npz

Permettent de sauvegarder un ou plusieurs ndarray(s).

* npy: un seul tableau
* npz: plusieurs tableaux avec leurs noms

Les données sont compressées.

Lire et écrire un tableau dans un fichier `npy` avec `np.load` et `np.save`.

a = np.random.randn(4,5)
print(a)

In [30]:
np.save("mon_tableau.npy", arr=a)

In [31]:
b = np.load("mon_tableau.npy")
print(b)
print(a-b)

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]
 [35 36 37 38 39 40 41]]
[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


Lire et écrire plusieurs tableaux dans un fichier `npz` avec `np.load` et `np.savez`.

In [32]:
np.savez("mes_tableaux.npz", a=a, sonde48=b)
##%%
data = np.load("mes_tableaux.npz")
print(dict(data))
z = data['sonde48']
print(z)
print(b-z)

{'a': array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39, 40, 41]]), 'sonde48': array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39, 40, 41]])}
[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]
 [35 36 37 38 39 40 41]]
[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


Voir aussi: [np.savez_compressed](https://numpy.org/doc/stable/reference/generated/numpy.savez_compressed.html).


#### Format générique csv
Manipulation standard de fichiers `.csv` avec `np.savetxt` et `np.loadtxt` pour le stockage de données tabulaires: choix de l'entête, du délimiteur, etc.

In [33]:
a = np.arange(12, dtype=int).reshape(-1, 2)
print(a)
np.savetxt("mon_tableau.csv", X=a, header="x, y", delimiter=",")
b = np.loadtxt("mon_tableau.csv", delimiter=",")
print(b)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
[[ 0.  1.]
 [ 2.  3.]
 [ 4.  5.]
 [ 6.  7.]
 [ 8.  9.]
 [10. 11.]]


In [34]:
!cat mon_tableau.csv

# x, y
0.000000000000000000e+00,1.000000000000000000e+00
2.000000000000000000e+00,3.000000000000000000e+00
4.000000000000000000e+00,5.000000000000000000e+00
6.000000000000000000e+00,7.000000000000000000e+00
8.000000000000000000e+00,9.000000000000000000e+00
1.000000000000000000e+01,1.100000000000000000e+01


Voir aussi: [pandas](https://pandas.pydata.org/).

### Autres fonctions de base

Exemple de la somme:

In [35]:
a = np.arange(12, dtype=int).reshape(-1, 2)
print(a)
print('Somme de tous les éléments:', np.sum(a))
print('Somme verticalement:', np.sum(a, axis=0))
print('Somme horizontalement:', np.sum(a, axis=1))

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
Somme de tous les éléments: 66
Somme verticalement: [30 36]
Somme horizontalement: [ 1  5  9 13 17 21]


De nombreuses autres fonctions dans le même genre:
* `np.prod`: produit
* `np.diff`: différence entre éléments consécutifs
* `np.cumsum`: somme cumulée
* `np.cumprod`: produit cumulé
* `np.mean`: moyenne
* `np.std`: écart-type
* `np.min`, `np.argmin`, `np.max`, `np.argmax`: min, max
* `np.sort`, `np.argsort`: tri
* etc.

Sous-modules:

* `np.random`: générateurs aléatoires
* `np.linalg`: algèbre linéaire
* `np.fft`: transformée de Fourier
* `np.testing`: pour des tests unitaires avec des ndarray
* `np.matrix`: type spécifique pour les matrices, **obsolète**.

## Manipulations avancées

### Broadcasting
= redimensionnement naturel si opérations entre tableaux de tailles différentes

---
$$
\begin{pmatrix}
a_{11} & a_{12} & \ldots & a_{1N}\\
\vdots & \vdots & \vdots & \vdots\\
a_{M1} & a_{M2} & \ldots & a_{MN}\\
\end{pmatrix}
+ b
=
\begin{pmatrix}
a_{11} + b & a_{12} + b & \ldots & a_{1N}+ b \\
\vdots & \vdots & \vdots & \vdots\\
a_{M1} + b & a_{M2}+ b  & \ldots & a_{MN}+ b \\
\end{pmatrix}
$$

$$
=
\begin{pmatrix}
a_{11} & a_{12} & \ldots & a_{1N}\\
\vdots & \vdots & \vdots & \vdots\\
a_{M1} & a_{M2} & \ldots & a_{MN}\\
\end{pmatrix}
+
\begin{pmatrix}
b & b & \ldots & b\\
\vdots & \vdots & \vdots & \vdots\\
b & b & \ldots & b\\
\end{pmatrix}
$$

In [36]:
# Addition d'un valeur
a = np.arange(6).reshape(2, 3)
print(a)
print(a + 2)

[[0 1 2]
 [3 4 5]]
[[2 3 4]
 [5 6 7]]


---
$$
\begin{pmatrix}
a_{11} & a_{12} & \ldots & a_{1N}\\
\vdots & \vdots & \vdots & \vdots\\
a_{M1} & a_{M2} & \ldots & a_{MN}\\
\end{pmatrix}
+
\begin{pmatrix}
b_{1} & b_{2} & \ldots & b_{N}\\
\end{pmatrix}
=
\begin{pmatrix}
a_{11} & a_{12} & \ldots & a_{1N}\\
\vdots & \vdots & \vdots & \vdots\\
a_{M1} & a_{M2} & \ldots & a_{MN}\\
\end{pmatrix}
+
\begin{pmatrix}
b_{1} & b_{2} & \ldots & b_{N}\\
\vdots & \vdots & \vdots & \vdots\\
b_{1} & b_{2} & \ldots & b_{N}\\
\end{pmatrix}
$$

$$
=
\begin{pmatrix}
a_{11} + b_{1} & a_{12} + b_{2}& \ldots & a_{1N} + b_{N}\\
\vdots & \vdots & \vdots & \vdots\\
a_{M1} + b_{1} & a_{M2} + b_{2} & \ldots & a_{MN} + b_{N}\\
\end{pmatrix}
$$

In [37]:
a = np.arange(6).reshape(2, 3)
b = np.arange(3).reshape(1, 3)  # b est de dimensions (1, 3)
print(a)
print(b)
print(a + b)

[[0 1 2]
 [3 4 5]]
[[0 1 2]]
[[0 2 4]
 [3 5 7]]


---
$$
\begin{pmatrix}
a_{1} & a_{2} & \ldots & a_{N}\\
\end{pmatrix}
+
\begin{pmatrix}
b_{1} \\ \vdots \\ b_{M}\\
\end{pmatrix}
=
\begin{pmatrix}
a_{1} & a_{2} & \ldots & a_{N}\\
\vdots & \vdots & \vdots & \vdots\\
a_{1} & a_{2} & \ldots & a_{N}\\
\end{pmatrix}
+
\begin{pmatrix}
b_{1} & b_{1} & \ldots & b_{1}\\
\vdots & \vdots & \vdots & \vdots\\
b_{M} & b_{M} & \ldots & b_{M}\\
\end{pmatrix}
$$
$$=
\begin{pmatrix}
a_{1} + b_{1} & a_{2} + b_{1}& \ldots & a_{N} + b_{1}\\
\vdots & \vdots & \vdots & \vdots\\
a_{1} + b_{M} & a_{2} + b_{M} & \ldots & a_{N} + b_{M}\\
\end{pmatrix}
$$

In [38]:
a = np.arange(3).reshape(1, 3)  # 1 est de dimensions (1, 3)
b = np.arange(2).reshape(2, 1)  # b est de dimensions (2, 1)
print(a)
print(b)
print(a + b)

[[0 1 2]]
[[0]
 [1]]
[[0 1 2]
 [1 2 3]]


---
Règle de broadcasting: on peut effectuer un broadcasting entre deux tableaux de dimensions $d_1 \times d_2 \times \ldots \times d_n$ et $e_1 \times e_2 \times \ldots \times e_n$ si pour chaque dimension $i$, l'un des deux cas est vérifié:
* les deux dimensions sont égale: $d_i=e_i$
* une des deux dimensions vaut $1$: $d_i=1$ ou $e_i=1$

Si les deux tableaux n'ont pas le même nombre de dimensions, on applique la règle *de droite à gauche* puis on complète par des $1$



Exemples:

|           |    |    |    |
|:---------:|:--:|:--:|:--:|
| Tableau 1 | 10 | 10 | 1  |
| Tableau 2 | 10 |  1 | 2  |
| Résultat  | 10 | 10 | 2  |

|           |    |    |    |
|:---------:|:--:|:--:|:--:|
| Tableau 1 | 10 | 10 | 2  |
| Tableau 2 |    |    | 2  |
| Résultat  | 10 | 10 | 2  |


|           |   |   |   |   |
|:---------:|:-:|:-:|:-:|:-:|
| Tableau 1 | 8 | 1 | 6 | 1 | 
| Tableau 2 |   | 7 | 1 | 5 |
| Résultat  | 8 | 7 | 6 | 5 |

Voir aussi: [documentation officielle sur le broadcasting](https://numpy.org/doc/stable/user/basics.broadcasting.html).

### Indexation avancée
Voir aussi: [Documentation officielle numpy sur l'indexation](https://numpy.org/doc/stable/user/basics.indexing.html)

**Indexation simple**: `a[obj]` où `obj` est un entier (`a[3]`), un tuple d'entiers (`a[2, 3]`), un slice (`a[1:5, 0, :]`) $\rightarrow$ vu plus haut.

**Indexation avancée**: `a[obj]` où `obj` fait notamment intervenir des séquences d'entiers ou de booléens.

#### Indexation avancée avec des séquences d'entiers

Cas 1D : `obj` désigne les indices à retenir. L'ordre peut être arbitraire, les répétitions sont possibles.

In [39]:
a = np.arange(0, 200, 10)
obj = [0, 0, 1, 3, 5, 6, 1]
b = a[obj]
print("a =", a)
print("b =", b)
print("  =", a[[0, 0, 1, 3, 5, 6, 1]]) # idem sans variable intermédiaire

a = [  0  10  20  30  40  50  60  70  80  90 100 110 120 130 140 150 160 170
 180 190]
b = [ 0  0 10 30 50 60 10]
  = [ 0  0 10 30 50 60 10]


Cas n-D: `obj` est un tuple de taille $n$, dont chaque élément est une séquence de même taille $m$. Résultat de taille $m$.

In [40]:
a = a.reshape(5, 4)
obj = [0, 2, 4], [0, 1, 0]
b = a[obj]  # 2 listes de taille 3
print("a =", a)
print("b =", b)
print("  =", a[[0, 2, 4], [0, 1, 0]])  # idem sans variable intermédiaire

a = [[  0  10  20  30]
 [ 40  50  60  70]
 [ 80  90 100 110]
 [120 130 140 150]
 [160 170 180 190]]
b = [  0  90 160]
  = [  0  90 160]


Les séquences d'indices peuvent être multi-dimensionnelles!

In [41]:
a = np.arange(10)
print("a =", a)
obj = np.array([[0, 0], [2, -1]])
print('Indices:')
print(obj)
print('Résultat:')
print(a[obj])

a = [0 1 2 3 4 5 6 7 8 9]
Indices:
[[ 0  0]
 [ 2 -1]]
Résultat:
[[0 0]
 [2 9]]


In [42]:
a = a.reshape(2, -1)
print("a =", a)
obj = np.array([[0, 0, 0], [1, -1, 1]]), np.array([[0, 1, 2], [2, 3, 4]])
print('Indices:')
print(obj[0])
print(obj[1])
print('Résultat:')
print(a[obj])

a = [[0 1 2 3 4]
 [5 6 7 8 9]]
Indices:
[[ 0  0  0]
 [ 1 -1  1]]
[[0 1 2]
 [2 3 4]]
Résultat:
[[0 1 2]
 [7 8 9]]


À retenir: `result = x[ind_1, ind_2, ..., ind_N]` avec des séquences d'entiers `ind_x` revient à faire, pour chaque coefficient

`result[i_1, ..., i_M] == x[ind_1[i_1, ..., i_M], ind_2[i_1, ..., i_M], ..., ind_N[i_1, ..., i_M]]`

`result` et les `ind_x` ont les mêmes dimensions.

**Autre cas utile:** sélectionner un sous-tableau en donnant les indices selon chaqueÀ retenir: `result = x[ind_1, ind_2, ..., ind_N]` avec des séquences d'entiers `ind_x` revient à faire, pour chaque coefficient

`result[i_1, ..., i_M] == x[ind_1[i_1, ..., i_M], ind_2[i_1, ..., i_M], ..., ind_N[i_1, ..., i_M]]`

`result` et les `ind_x` ont les mêmes dimensions.

**Autre cas utile:** sélectionner un sous-tableau en donnant les indices selon chaque dimension.

$\rightarrow$ utiliser `np.ix_`.

Exemple: la sous-matrice de $a$ composée des lignes 1 et 2 et des colonne 0, 2, 3.

In [43]:
a = np.arange(12).reshape(3, 4)
b = a[np.ix_((1, 2), (0, 2, 3))]
print(a)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 4  6  7]
 [ 8 10 11]]


#### Indexation avancée avec des booléens

$\rightarrow$ `a[obj]` où `obj` contient des booléens.

Cas utile: `a` et `obj` sont de mêmes dimensions (voir [documentation](https://numpy.org/doc/stable/user/basics.indexing.html#boolean-array-indexing) pour le cas plus général).

Renvoie un tableau 1D avec les éléments de `a` pour lesquels `obj` est `True` (C-order).

In [44]:
a = np.arange(15)  # Cas 1D
print(a)
print(a % 2 == 0)
print(a[a % 2 == 0])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ True False  True False  True False  True False  True False  True False
  True False  True]
[ 0  2  4  6  8 10 12 14]


In [45]:
a = np.arange(15, dtype=float).reshape(3, -1)  # Cas 2D
print(a)
print(a % 2 == 0)
print(a[a % 2 == 0])

[[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]]
[[ True False  True False  True]
 [False  True False  True False]
 [ True False  True False  True]]
[ 0.  2.  4.  6.  8. 10. 12. 14.]


In [46]:
a[a % 2 == 1] = np.nan
print(a)

[[ 0. nan  2. nan  4.]
 [nan  6. nan  8. nan]
 [10. nan 12. nan 14.]]


## Vues et copies

Notion de **vue** (*view*): certaines manipulations créent une présentation des éléments d'un tableau sans les recopier.

$\rightarrow$ plus rapide mais attention aux modifications!

In [47]:
a = np.arange(8)
b = a[1:5]
print(a)
b = a[1:5]
print(a)
print(b)
b[0] = 9
print(a)
print(b)

[0 1 2 3 4 5 6 7]
[0 1 2 3 4 5 6 7]
[1 2 3 4]
[0 9 2 3 4 5 6 7]
[9 2 3 4]


Manipulations créant une vue:
* `reshape`
* indexation simple avec `start:stop` et `start:stop:step`

In [48]:
a = np.arange(12)
b = a.reshape(2, 6)  # Une vue par reshape
c = b[0, ::2]  # Une vue par indexation simple
print('a =', a)
print('b =\n', b)
print('c =', c)
c[0] = -1  # Une modification
print('a =', a)  # Modifié
print('b =\n', b)  # Modifié
print('c =', c)

a = [ 0  1  2  3  4  5  6  7  8  9 10 11]
b =
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
c = [0 2 4]
a = [-1  1  2  3  4  5  6  7  8  9 10 11]
b =
 [[-1  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
c = [-1  2  4]


Manipulations créant une copie:
* `copy`
* indexation avancée

In [49]:
a = np.arange(12)
b = a.reshape(2, 6).copy()  # une copie explicite
c = b[0, np.arange(0, 6, 2)]  # Copie par indexation avancée avec des entiers
d = b[0, [True, False] * 3]  # Copie par indexation avancée avec des booléens
b[0, 0] = -1  # Une modification
print('a =', a)  # Non-modifié
print('b =\n', b)
print('c =', c)  # Non-modifié
print('d =', d)  # Non-modifié

a = [ 0  1  2  3  4  5  6  7  8  9 10 11]
b =
 [[-1  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
c = [0 2 4]
d = [0 2 4]


**Affectation vs. vue**
L'affectation n'est pas une vue, on obtient exactement le même objet.
On peut créer une vue avec `view`

In [50]:
a = np.arange(5)
b = a  # Affectation
print(b is a)  # Est-ce le même objet? Oui!
c = a.view()  # Vue
print(c is a)  # Est-ce le même objet? Non!
a[0] = 9
print(a)
print(b)
print(c)

True
False
[9 1 2 3 4]
[9 1 2 3 4]
[9 1 2 3 4]


# Quelques mots sur `panda`


In [51]:
#!pip install pandas
import pandas as pd

## Series
Le premier type de données apporté par pandas est la Series, qui correspond à un vecteur à une dimension.

In [52]:
s = pd.Series([100, 200, 300, 40], index = ['a', 'b', 'c', 'd'])
s

a    100
b    200
c    300
d     40
dtype: int64

### Sélections par étiquette ou indice
Avec pandas, chaque élément de la série de données possède une étiquette qui permet d'appeler les éléments qui la composent. 
Ainsi, pour appeler le premier élément de la série, on peut utiliser son étiquette (ici, "a") :

In [53]:
s["a"]

np.int64(100)

#### Modifications de Series
Les étiquettes permettent de modifier et d'ajouter des éléments :

In [54]:
s["c"] = 300
s["z"] = 50
s

a    100
b    200
c    300
d     40
z     50
dtype: int64

### Les Filtres

In [55]:
s[(s>20) & (s<100)]

d    40
z    50
dtype: int64

## Dataframes
Ils correspondent à des tableaux à deux dimensions avec des étiquettes pour nommer les lignes et les colonnes.

In [56]:
import numpy as np
df = pd.DataFrame(columns=["a", "b", "c", "d"],
                  index=["chat", "singe", "souris"],
                  data=[np.arange(10, 14),
                        np.arange(20, 24),
                        np.arange(30, 34)])
df

a   b   c   d
chat    10  11  12  13
singe   20  21  22  23
souris  30  31  32  33

In [57]:
data = {"a": np.arange(10, 40, 10),
        "b": np.arange(11, 40, 10),
        "c": np.arange(12, 40, 10),
        "d": np.arange(13, 40, 10)}
df = pd.DataFrame(data)
df.index = ["chat", "singe", "souris"]
df

a   b   c   d
chat    10  11  12  13
singe   20  21  22  23
souris  30  31  32  33

## Création à partir de fichiers

In [58]:
df = pd.read_csv("rawPPI_network_nodeTable.csv")
df

SUID  AverageShortestPathLength  BetweennessCentrality  \
0          72                   2.836233               0.005481   
1          73                   2.907954               0.002961   
2          75                   2.829142               0.003529   
3          77                   2.995175               0.000892   
4          79                   2.904884               0.002721   
...       ...                        ...                    ...   
13674  104120                   4.486913               0.000000   
13675  104122                   4.486913               0.000000   
13676  104126                   4.946995               0.000000   
13677  104128                   6.070332               0.000000   
13678  104133                   6.080348               0.000000   

       ClosenessCentrality  ClusteringCoefficient  Degree  Eccentricity  \
0                 0.352580               0.035485     244             6   
1                 0.343884               0.021468     137             6   
2                 0.353464               0.060243     123             6   
3                 0.333870               0.101090     117             6   
4                 0.344248               0.023420     136             7   
...                    ...                    ...     ...           ...   
13674             0.222870               0.000000       1             8   
13675             0.222870               0.000000       1             8   
13676             0.202143               0.000000       1             8   
13677             0.164736               0.000000       1             9   
13678             0.164464               0.000000       1             9   

       IsSingleNode    name  NeighborhoodConnectivity  NumberOfDirectedEdges  \
0             False  Q93062                 47.795082                    244   
1             False  Q8N9N5                 46.343066                    137   
2             False  O95967                 80.447154                    123   
3             False  P59991                 70.931624                    117   
4             False  P78424                 49.772059                    136   
...             ...     ...                       ...                    ...   
13674         False  Q7Z5D8                 19.000000                      1   
13675         False  A6NKC6                 19.000000                      1   
13676         False  A4D2P6                  3.000000                      1   
13677         False  P33076                  3.000000                      1   
13678         False  P23219                  2.000000                      1   

       NumberOfUndirectedEdges  PartnerOfMultiEdgedNodePairs  Radiality  \
0                            0                             0   0.816377   
1                            0                             0   0.809205   
2                            0                             0   0.817086   
3                            0                             0   0.800483   
4                            0                             0   0.809512   
...                        ...                           ...        ...   
13674                        0                             0   0.651309   
13675                        0                             0   0.651309   
13676                        0                             0   0.605300   
13677                        0                             0   0.492967   
13678                        0                             0   0.491965   

       selected  SelfLoops shared name    Stress  TopologicalCoefficient  
0         False          0      Q93062  27684680                0.013493  
1         False          0      Q8N9N5  11643156                0.015641  
2         False          0      O95967  14271130                0.020935  
3         False          0      P59991   4818360                0.026755  
4         False          0      P78424  11167158                0.

In [59]:
df = pd.read_csv("rawPPI_network_nodeTable.csv", index_col="SUID")
df.head()

AverageShortestPathLength  BetweennessCentrality  ClosenessCentrality  \
SUID                                                                          
72                     2.836233               0.005481             0.352580   
73                     2.907954               0.002961             0.343884   
75                     2.829142               0.003529             0.353464   
77                     2.995175               0.000892             0.333870   
79                     2.904884               0.002721             0.344248   

      ClusteringCoefficient  Degree  Eccentricity  IsSingleNode    name  \
SUID                                                                      
72                 0.035485     244             6         False  Q93062   
73                 0.021468     137             6         False  Q8N9N5   
75                 0.060243     123             6         False  O95967   
77                 0.101090     117             6         False  P59991   
79                 0.023420     136             7         False  P78424   

      NeighborhoodConnectivity  NumberOfDirectedEdges  \
SUID                                                    
72                   47.795082                    244   
73                   46.343066                    137   
75                   80.447154                    123   
77                   70.931624                    117   
79                   49.772059                    136   

      NumberOfUndirectedEdges  PartnerOfMultiEdgedNodePairs  Radiality  \
SUID                                                                     
72                          0                             0   0.816377   
73                          0                             0   0.809205   
75                          0                             0   0.817086   
77                          0                             0   0.800483   
79                          0                             0   0.809512   

      selected  SelfLoops shared name    Stress  TopologicalCoefficient  
SUID                                                                     
72       False          0      Q93062  27684680                0.013493  
73       False          0      Q8N9N5  11643156                0.015641  
75       False          0      O95967  14271130                0.020935  
77       False          0      P59991   4818360                0.026755  
79       False          0      P78424  11167158                0.015982

In [60]:
df["selected"].value_counts()

selected
False    13679
Name: count, dtype: int64

**Questions?**

*Récap*

Place à la pratique!

In [61]:
!jupyter nbconvert --to html --allow-chromium-download 2.numpy-ndarray.ipynb

[NbConvertApp] Converting notebook 2.numpy-ndarray.ipynb to html
[NbConvertApp] Writing 423702 bytes to 2.numpy-ndarray.html


In [63]:
!jupyter nbconvert --to slides 2.numpy-ndarray.ipynb

[NbConvertApp] Converting notebook 2.numpy-ndarray.ipynb to slides
[NbConvertApp] Writing 453527 bytes to 2.numpy-ndarray.slides.html
